<?php

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customers')->delete();
        
        \DB::table('customers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'first_name' => 'Richmond Customer',
                'last_name' => NULL,
                'company' => 'Batteries Included',
                'address' => '5300 No 3 Rd',
                'city' => 'Richmond',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => 'V6X 2C7',
                'primary_phone' => '604-270-9989',
                'secondary_phone' => NULL,
                'email' => 'richmond@batteriesincluded.ca',
                'comments' => NULL,
                'store_credit' => NULL,
                'location_id' => 2,
                'created_at' => '2017-08-01 13:08:38',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'first_name' => 'White Rock Customer',
                'last_name' => NULL,
                'company' => 'Batteries Included',
                'address' => '1711 152nd Street',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => 'V4A 4N3',
                'primary_phone' => '604-536-8108',
                'secondary_phone' => NULL,
                'email' => 'whiterock@batteriesincluded.ca',
                'comments' => NULL,
                'store_credit' => NULL,
                'location_id' => 3,
                'created_at' => '2017-08-01 13:08:38',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'first_name' => 'Guildford Customer',
                'last_name' => NULL,
                'company' => 'Batteries Included',
                'address' => 'Unit 101J, 15277 - 100th Ave',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => 'V3R 8X2',
                'primary_phone' => '604-930-9889',
                'secondary_phone' => NULL,
                'email' => 'guildford@batteriesincluded.ca',
                'comments' => NULL,
                'store_credit' => NULL,
                'location_id' => 6,
                'created_at' => '2017-08-01 13:08:38',
                'updated_at' => '2017-08-04 15:49:07',
            ),
            3 => 
            array (
                'id' => 4,
                'first_name' => 'Ronnie',
                'last_name' => 'Dizom',
                'company' => '',
                'address' => '',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-616-3576',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-01 14:28:31',
                'updated_at' => '2017-08-01 14:28:31',
            ),
            4 => 
            array (
                'id' => 5,
                'first_name' => 'Phuong Nyugen',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-722-3829',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-02 14:33:32',
                'updated_at' => '2017-08-02 14:33:32',
            ),
            5 => 
            array (
                'id' => 6,
                'first_name' => 'Jenny Hassan',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-996-6964',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-02 14:47:19',
                'updated_at' => '2017-08-02 14:47:19',
            ),
            6 => 
            array (
                'id' => 7,
                'first_name' => 'Peter Jackson',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => 'Langley',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-888-9459',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-03 14:49:37',
                'updated_at' => '2017-08-03 14:49:37',
            ),
            7 => 
            array (
                'id' => 8,
                'first_name' => 'Liza',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '778-908-7804',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-03 14:51:19',
                'updated_at' => '2017-08-03 14:51:19',
            ),
            8 => 
            array (
                'id' => 9,
                'first_name' => 'Kim',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => '',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '778-394-7426',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-04 14:56:02',
                'updated_at' => '2017-08-04 14:56:02',
            ),
            9 => 
            array (
                'id' => 10,
                'first_name' => 'Tom',
                'last_name' => 'Bourne',
                'company' => '',
                'address' => '',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-551-1143',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-05 17:25:27',
                'updated_at' => '2017-08-05 17:25:27',
            ),
            10 => 
            array (
                'id' => 11,
                'first_name' => 'Marie',
                'last_name' => 'Wright',
                'company' => '',
                'address' => '',
                'city' => '',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-853-1222',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-08 17:51:57',
                'updated_at' => '2017-08-08 17:51:57',
            ),
            11 => 
            array (
                'id' => 12,
                'first_name' => 'Jill',
                'last_name' => 'Schlecker',
                'company' => '',
                'address' => '',
                'city' => '',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-385-3856',
                'secondary_phone' => '604-785-3776',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-08 18:00:41',
                'updated_at' => '2017-08-08 18:00:41',
            ),
            12 => 
            array (
                'id' => 13,
                'first_name' => 'Shelby',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => '',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-868-0569',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-09 18:15:41',
                'updated_at' => '2017-08-09 18:15:41',
            ),
            13 => 
            array (
                'id' => 14,
                'first_name' => 'Rick',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => '',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-319-6235',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-10 13:43:05',
                'updated_at' => '2017-08-10 13:43:05',
            ),
            14 => 
            array (
                'id' => 15,
                'first_name' => 'Thomas',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => '',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '778-926-0694',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-11 13:55:09',
                'updated_at' => '2017-08-11 13:55:09',
            ),
            15 => 
            array (
                'id' => 16,
                'first_name' => 'Sergio Moran',
                'last_name' => '',
                'company' => '',
                'address' => 'Unit 59, 10535 - 153 Street',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => 'V3R4H7',
                'primary_phone' => '604-354-9197',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-12 14:04:19',
                'updated_at' => '2017-08-12 14:04:19',
            ),
            16 => 
            array (
                'id' => 17,
                'first_name' => 'Joyce Lyoo',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-773-7180',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-12 14:24:22',
                'updated_at' => '2017-08-12 14:24:22',
            ),
            17 => 
            array (
                'id' => 18,
                'first_name' => 'Giomar Rangel',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '778-834-2902',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-13 15:38:08',
                'updated_at' => '2017-08-13 15:38:08',
            ),
            18 => 
            array (
                'id' => 19,
                'first_name' => 'Brian Nevins',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-506-3956',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-13 15:42:42',
                'updated_at' => '2017-08-13 15:42:42',
            ),
            19 => 
            array (
                'id' => 20,
                'first_name' => 'Marven Adriano',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '778-883-9703',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-13 16:25:33',
                'updated_at' => '2017-08-13 16:25:33',
            ),
            20 => 
            array (
                'id' => 21,
                'first_name' => 'Les McCrae',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => '',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '778-862-0233',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-14 16:37:33',
                'updated_at' => '2017-08-14 16:37:33',
            ),
            21 => 
            array (
                'id' => 22,
                'first_name' => 'Gloria',
                'last_name' => 'Taylor',
                'company' => '',
                'address' => '16820 84 Ave',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => 'V4N4V3',
                'primary_phone' => '604-506-8941',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-14 16:52:34',
                'updated_at' => '2017-08-14 16:52:34',
            ),
            22 => 
            array (
                'id' => 23,
                'first_name' => 'Jagit',
                'last_name' => 'Sighn',
                'company' => '',
                'address' => '13261 79 ave',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => 'V3W6P2',
                'primary_phone' => '778-337-2756',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-19 14:58:58',
                'updated_at' => '2017-08-19 14:58:58',
            ),
            23 => 
            array (
                'id' => 24,
                'first_name' => 'Melvin',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '778-779-1386',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-19 17:26:47',
                'updated_at' => '2017-08-19 17:26:47',
            ),
            24 => 
            array (
                'id' => 25,
                'first_name' => 'Joseph',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => '',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-880-7544',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-20 13:17:01',
                'updated_at' => '2017-08-20 13:17:01',
            ),
            25 => 
            array (
                'id' => 26,
                'first_name' => 'Chris',
                'last_name' => 'Nedd',
                'company' => '',
                'address' => '319-7297 138st',
                'city' => 'Surrey',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => 'V3W0E5',
                'primary_phone' => '778-689-1521',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-20 13:27:12',
                'updated_at' => '2017-08-20 13:27:12',
            ),
            26 => 
            array (
                'id' => 27,
                'first_name' => 'Lu',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => '',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-729-6586',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-20 13:52:29',
                'updated_at' => '2017-08-20 13:52:29',
            ),
            27 => 
            array (
                'id' => 28,
                'first_name' => 'Johl',
                'last_name' => '',
                'company' => '',
                'address' => '',
                'city' => '',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-372-3012',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-22 14:15:18',
                'updated_at' => '2017-08-22 14:15:18',
            ),
            28 => 
            array (
                'id' => 29,
                'first_name' => 'Jane',
                'last_name' => 'Bartel',
                'company' => '',
                'address' => '60-8254 134st',
                'city' => '',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => 'V3W6M2',
                'primary_phone' => '778-590-8505',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-24 14:27:40',
                'updated_at' => '2017-08-24 14:27:40',
            ),
            29 => 
            array (
                'id' => 30,
                'first_name' => 'Gabrielle',
                'last_name' => 'Lan',
                'company' => '',
                'address' => '1607 388 Home Street',
                'city' => 'Vancouver',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '778-987-0607',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-26 14:34:56',
                'updated_at' => '2017-08-26 14:34:56',
            ),
            30 => 
            array (
                'id' => 31,
                'first_name' => 'Henry',
                'last_name' => 'Schaafsma',
                'company' => '',
                'address' => '',
                'city' => '',
                'province' => 'British Columbia',
                'country' => 'Canada',
                'postal_code' => '',
                'primary_phone' => '604-888-0882',
                'secondary_phone' => '',
                'email' => '',
                'comments' => '',
                'store_credit' => 0,
                'location_id' => 6,
                'created_at' => '2017-08-15 14:44:46',
                'updated_at' => '2017-08-15 14:44:46',
            ),
        ));
        
        
    }
}
